#include "NoisyNodes/ClassicNoise3D.hlsl"
#include "NoisyNodes/Voronoi3D.hlsl"

#pragma kernel GeneratePlanet

#define MountainNoise 0
#define WarpingNoise 1

// Structs
struct PerlinNoiseSettings
{
    float amplitude;
    float frequency;
    float persistance;
    float lacunarity;
    int octaves;
};


float PlanetRadius;

// Vertices should all have a modulus of 1 at this point
RWStructuredBuffer<float3> vertices;

float3 NoiseOffset;

// Noise settings
RWStructuredBuffer<PerlinNoiseSettings> PerlinSettings;

float PerlinNoise(float3 pos, float3 offset, float amplitude, float frequency, float persistance, float lacunarity, int octaves);


[numthreads(64,1,1)]
void GeneratePlanet (uint3 id : SV_DispatchThreadID)
{
    uint numVertices;
    uint vertexStride;
    vertices.GetDimensions(numVertices, vertexStride);
    [flatten] if (id.x >= numVertices)
    {
        return;
    }
    
    float3 pos = vertices[id.x];
    float terrainHeight = PlanetRadius;
    float warpingNoise = PlanetRadius * PerlinNoise(pos, NoiseOffset, PerlinSettings[WarpingNoise].amplitude,
                                                       PerlinSettings[WarpingNoise].frequency,
                                                       PerlinSettings[WarpingNoise].persistance,
                                                       PerlinSettings[WarpingNoise].lacunarity,
                                                       PerlinSettings[WarpingNoise].octaves);
    
    // Mountain scale noise
    float mountainNoise = PlanetRadius * PerlinNoise(pos + warpingNoise, NoiseOffset, PerlinSettings[MountainNoise].amplitude,
                                                       PerlinSettings[MountainNoise].frequency,
                                                       PerlinSettings[MountainNoise].persistance,
                                                       PerlinSettings[MountainNoise].lacunarity,
                                                       PerlinSettings[MountainNoise].octaves);
    mountainNoise = abs(mountainNoise);
    terrainHeight += mountainNoise;
    
    
    vertices[id.x] *= terrainHeight;
}


float PerlinNoise(float3 pos, float3 offset, float amplitude, float frequency, float persistance, float lacunarity, int octaves)
{
    
    float noiseValue = 0;
    for (int i = 0; i < octaves; i++)
    {
        noiseValue += amplitude * PerlinNoise3D_float(frequency * pos + offset);
        amplitude *= persistance;
        frequency *= lacunarity;
    }
    
    return noiseValue;
}